import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MerchantProvider } from '@/contexts/merchant-context';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Tracker Merchant-Mandiri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
          <MerchantProvider>
            {children}
          </MerchantProvider>
      </body>
    </html>
  );
}
